Conform to shell style guide

diff --git a/bin/dclogs b/bin/dclogs
--- a/bin/dclogs
+++ b/bin/dclogs
@@ -2,14 +2,24 @@
 set -eu -o pipefail
 
 check_command() {
-  command -v "$1" > /dev/null 2>&1 || { echo -e "\033[36m$1 not found\033[0m"; exit 1; }
+  command -v "$1" >/dev/null 2>&1 || {
+    echo -e "\033[36m$1 not found\033[0m"
+    exit 1
+  }
 }
 
-DOCKER=$(command -v podman || command -v docker); readonly DOCKER
+DOCKER=$(command -v podman || command -v docker)
+readonly DOCKER
 
 check_command dcls
 check_command fzy
 
-CONTAINER_ID="$(dcls | fzy | awk '{print $1}')"; readonly CONTAINER_ID
-[[ -n "$CONTAINER_ID" ]] || { echo -e "\033[36mNo container specified\033[0m"; exit 1; }
+CONTAINER_ID="$(dcls | fzy | awk '{print $1}')"
+readonly CONTAINER_ID
+
+if [[ -z "$CONTAINER_ID" ]]; then
+  echo -e "\033[36mNo container specified\033[0m"
+  exit 1
+fi
+
 $DOCKER container logs "$CONTAINER_ID" |& less
diff --git a/bin/dcls b/bin/dcls
--- a/bin/dcls
+++ b/bin/dcls
@@ -2,37 +2,42 @@
 set -eu -o pipefail
 
 check_command() {
-  command -v "$1" > /dev/null 2>&1 || { echo -e "\033[36m$1 not found\033[0m"; exit 1; }
+  command -v "$1" >/dev/null 2>&1 || {
+    echo -e "\033[36m$1 not found\033[0m"
+    exit 1
+  }
 }
 
-DOCKER=$(command -v podman || command -v docker); readonly DOCKER
+DOCKER=$(command -v podman || command -v docker)
+readonly DOCKER
 
 check_command "$DOCKER"
 check_command csvq
 
-T1=$(mktemp); readonly T1
-T2=$(mktemp); readonly T2
+T1=$(mktemp)
+readonly T1
+T2=$(mktemp)
+readonly T2
 
 $DOCKER container ls --format "{{.ID}},{{.Names}},{{.Image}},{{.CreatedAt}},{{.Status}}" -a >"$T1"
 
-if [[ $(wc -l < "$T1") -gt 0 ]]; then
+if [[ $(wc -l <"$T1") -gt 0 ]]; then
   # shellcheck disable=SC2046
   $DOCKER container inspect $($DOCKER container ls -aq) \
-    | csvq -i JSON -f CSV -N "SELECT substr(Id, 0, 12), substr(Image, 7, 12) FROM STDIN" \
-    >"$T2"
-    csvq -i CSV -n -f FIXED "
-      SELECT
-        t1.c1 AS CONTAINER_ID,
-        t1.c2 AS NAMES,
-        t2.c2 AS IMAGE_ID,
-        t1.c3 AS IMAGE,
-        t1.c4 AS CREATED,
-        t1.c5 AS STATUS
-      FROM
-        \`$T1\` AS t1,
-        \`$T2\` AS t2
-      WHERE t1.c1 = t2.c1
-    "
+    | csvq -i JSON -f CSV -N "SELECT substr(Id, 0, 12), substr(Image, 7, 12) FROM STDIN" >"$T2"
+  csvq -i CSV -n -f FIXED "
+    SELECT
+      t1.c1 AS CONTAINER_ID,
+      t1.c2 AS NAMES,
+      t2.c2 AS IMAGE_ID,
+      t1.c3 AS IMAGE,
+      t1.c4 AS CREATED,
+      t1.c5 AS STATUS
+    FROM
+      \`$T1\` AS t1,
+      \`$T2\` AS t2
+    WHERE t1.c1 = t2.c1
+  "
 fi
 
 rm "$T1" "$T2"
