Fix issue when a container does not exist

diff --git a/bin/dcls b/bin/dcls
--- a/bin/dcls
+++ b/bin/dcls
@@ -2,7 +2,7 @@
 set -eu -o pipefail
 
 check_command() {
-  command -v "$1" > /dev/null 2>&1 || echo -e "\033[36m$1 not found\033[0m"
+  command -v "$1" > /dev/null 2>&1 || { echo -e "\033[36m$1 not found\033[0m"; exit 1; }
 }
 
 check_command docker
@@ -13,8 +13,11 @@ readonly T1=$(mktemp)
 readonly T2=$(mktemp)
 
 docker container ls --format "{{.ID}},{{.Names}},{{.Image}},{{.RunningFor}},{{.Status}}" -a > "$T1"
-# shellcheck disable=SC2046
-docker container inspect $(docker ps -aq) | jq -r '.[] | [.Id[0:12], .Image[7:19]] | @csv' > "$T2"
+
+if [[ $(wc -l < "$T1") -gt 0 ]]; then
+  # shellcheck disable=SC2046
+  docker container inspect $(docker ps -aq) | jq -r '.[] | [.Id[0:12], .Image[7:19]] | @csv' > "$T2"
+fi
 
 q -d, -O -D, -b "SELECT t1.c1 AS CONTAINER_ID, t1.c2 AS NAMES, t2.c2 AS IMAGE_ID, t1.c3 AS IMAGE, t1.c4 AS CREATED, t1.c5 AS STATUS FROM $T1 AS t1 JOIN $T2 AS t2 ON (t1.c1 = t2.c1)" | sed 's/,/  /g'
 
